from pymongo import MongoClient
from datetime import datetime, timedelta

client = MongoClient("mongodb://localhost:27017/sae_jpo")
db = client["sae_jpo"]
db["visitors"].drop()
print("Collection visitors vidée.")

visitors = [
    {
        "first_name": "Alice",
        "last_name": "Martin",
        "email": "alice.martin@mail.com",
        "bac_type": "Général",
        "department": "Informatique",
        "ine": "1234567890A",
        "reorientation": False,
        "dossier_particulier": False,
        "specialite_1": "Mathématiques",
        "specialite_2": "NSI",
        "etablissement": "Lycée Henri IV",
        "ville": "Paris",
        "immersion": True,
        "created_at": datetime.now() - timedelta(days=1),
        "visit_count": 1,
    },
    {
        "first_name": "Lucas",
        "last_name": "Dupont",
        "email": "lucas.dupont@mail.com",
        "bac_type": "STI2D",
        "department": "GEII",
        "ine": None,
        "reorientation": False,
        "dossier_particulier": False,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Galilée",
        "ville": "Noisy-le-Grand",
        "immersion": False,
        "created_at": datetime.now() - timedelta(days=1),
        "visit_count": 1,
    },
    {
        "first_name": "Camille",
        "last_name": "Bernard",
        "email": "camille.bernard@mail.com",
        "bac_type": "Général",
        "department": "MMI",
        "ine": "9876543210B",
        "reorientation": True,
        "dossier_particulier": False,
        "specialite_1": "Arts",
        "specialite_2": "Histoire-Géo",
        "etablissement": "Lycée Lumière",
        "ville": "Montreuil",
        "immersion": True,
        "created_at": datetime.now() - timedelta(hours=5),
        "visit_count": 2,
    },
    {
        "first_name": "Noah",
        "last_name": "Petit",
        "email": "noah.petit@mail.com",
        "bac_type": "STMG",
        "department": "TC",
        "ine": None,
        "reorientation": False,
        "dossier_particulier": True,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Jean Jaurès",
        "ville": "Vincennes",
        "immersion": False,
        "created_at": datetime.now() - timedelta(hours=3),
        "visit_count": 1,
    },
    {
        "first_name": "Emma",
        "last_name": "Leroy",
        "email": "emma.leroy@mail.com",
        "bac_type": "Général",
        "department": "Informatique",
        "ine": "1122334455C",
        "reorientation": False,
        "dossier_particulier": False,
        "specialite_1": "Mathématiques",
        "specialite_2": "Physique-Chimie",
        "etablissement": "Lycée Descartes",
        "ville": "Rosny-sous-Bois",
        "immersion": True,
        "created_at": datetime.now() - timedelta(hours=2),
        "visit_count": 1,
    },
    {
        "first_name": "Hugo",
        "last_name": "Moreau",
        "email": "hugo.moreau@mail.com",
        "bac_type": "Pro",
        "department": "GEII",
        "ine": None,
        "reorientation": True,
        "dossier_particulier": False,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Pro Montreuil",
        "ville": "Montreuil",
        "immersion": False,
        "created_at": datetime.now() - timedelta(hours=1),
        "visit_count": 1,
    },
    {
        "first_name": "Léa",
        "last_name": "Simon",
        "email": "lea.simon@mail.com",
        "bac_type": "Général",
        "department": "GEA",
        "ine": "5566778899D",
        "reorientation": False,
        "dossier_particulier": False,
        "specialite_1": "SES",
        "specialite_2": "Histoire-Géo",
        "etablissement": "Lycée Voltaire",
        "ville": "Paris",
        "immersion": True,
        "created_at": datetime.now() - timedelta(minutes=45),
        "visit_count": 1,
    },
    {
        "first_name": "Tom",
        "last_name": "Laurent",
        "email": "tom.laurent@mail.com",
        "bac_type": "STI2D",
        "department": "Informatique",
        "ine": None,
        "reorientation": False,
        "dossier_particulier": True,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Léonard de Vinci",
        "ville": "Livry-Gargan",
        "immersion": False,
        "created_at": datetime.now() - timedelta(minutes=30),
        "visit_count": 1,
    },
    {
        "first_name": "Inès",
        "last_name": "Garcia",
        "email": "ines.garcia@mail.com",
        "bac_type": "ST2S",
        "department": "CS",
        "ine": None,
        "reorientation": True,
        "dossier_particulier": False,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Saint-Exupéry",
        "ville": "Bagnolet",
        "immersion": True,
        "created_at": datetime.now() - timedelta(minutes=15),
        "visit_count": 1,
    },
    {
        "first_name": "Axel",
        "last_name": "Roux",
        "email": "axel.roux@mail.com",
        "bac_type": "Autre",
        "department": "MMI",
        "ine": None,
        "reorientation": False,
        "dossier_particulier": False,
        "specialite_1": None,
        "specialite_2": None,
        "etablissement": "Lycée Picasso",
        "ville": "Fontenay-sous-Bois",
        "immersion": False,
        "created_at": datetime.now(),
        "visit_count": 1,
    },
]

result = db["visitors"].insert_many(visitors)
print(f" {len(result.inserted_ids)} visiteurs insérés dans sae_jpo.visitors")
print("Tu peux vérifier dans MongoDB Compass !")